channels:
  - bioconda
dependencies:
  - r-base=4.0
  - r-r.utils
  - r-knitr
  - r-data.table
  - r-rmarkdown
  - plink 
  - vcftools 
  - perl-vcftools-vcf 
  - bcftools 
  - ucsc-liftover
  - p7zip